### ISSUE TITLE
C++ headers

### ISSUE THREAD

**Issue by tomaklutfu** [buffer51/android-gfortran#4]
Is there a special reason for excluding c++ from toolchains. Or how I can add them correctly?

**Comment by buffer51** [comment]
Hi @tomaklutfu. I'm not sure to understand what you mean.

Are you referring to the fact that the folder `$(TOOLCHAIN)/include/` is empty in the toolchains? That is normal, in fact the folder should just be removed (like the prebuilt toolchains you can find in your NDK).

If you are using `ndk-build`, it should find headers under `$(NDK)/platforms/` automatically for you.
If not, and you are using the toolchains I built, the compiler should find them automatically under `$(TOOLCHAIN)/sysroot/`

**Comment by tomaklutfu** [comment]
Hi @buffer51 I actually wanted to say c++ headers and corresponding libraries at arm-linux-androideabi folder. Since they are excluded g++ in toolchains you provided cannot compile anything. If I add both of them from ndk files it works normally.

**Comment by buffer51** [comment]
Can you explain to me what you are building?

I just tried the arm-linux-androideabi on Linux to build OpenBLAS without an issue (simply added the `bin/` folder to my path and set the compiler to arm-linux-androideabi-gcc).

**Comment by buffer51** [comment]
The search path for `cpp` is:

```
$(TOOLCHAIN)/bin/../lib/gcc/arm-linux-androideabi/4.9.x/include
$(TOOLCHAIN)/bin/../lib/gcc/arm-linux-androideabi/4.9.x/include-fixed
$(TOOLCHAIN)/bin/../sysroot/usr/include
```

with most headers in the `sysroot/usr/include` folder.

**Comment by tomaklutfu** [comment]
As far as I know openblas doesn't have any c++ source code. Try this `Hello,world!` C++ code

``` C
#include <iostream>
int main()
{
    std::cout << "Hello, world!\n";
}
```

I got this

```
...@LTMLABS:~/Programming/arm-linux-androideabi-4.9/bin$ ./arm-linux-androideabi-gcc ./hello.cpp 
./hello.cpp:1:20: fatal error: iostream: No such file or directory
 #include <iostream>
                    ^
compilation terminated.
```

**Comment by buffer51** [comment]
Oh I see what you mean. Apologies. If you want to have the STL (which OpenBLAS doesn't require..), here's what to do:
- unpack the archive in your NDK (see the end of the README, as if you were going to use `ndk-build`).
- see [this](https://developer.android.com/ndk/guides/standalone_toolchain.html) for steps to recreate a standalone toolchain with the STL that you want (several available).

If this works for you, I'll update the README accordingly.

**Comment by tomaklutfu** [comment]
Thanks for reply. I didn't know it is called STL.
Just using this pseudo command

```
bash $NDK/build/tools/make-standalone-toolchain.sh --platform=android-$NUMBER --arch=$ARCH --install-dir=$INSTALLDIR
```

includes gnu stl library (libgnustl_shared.so and its static version).
Standalone toolchain with each of `--stl=STLVariant` (or lack of it like above) seems to work at least compiles and builds.

**Comment by buffer51** [comment]
Glad to hear it!
