### ISSUE TITLE
OpenBLAS does not build with platform 21+

### ISSUE THREAD

**Issue by tomaklutfu** [buffer51/android-gfortran#5]
While using a standalone toolchain with platform 21+ and ndk12,  mention that openblas gives error as such

```
/sysroot/usr/include/signal.h:113: error: undefined reference to 'bsd_signal'
```

http://stackoverflow.com/questions/36746904/android-linker-undefined-reference-to-bsd-signal
Above link is for reference. I can build with platform 19.

**Comment by buffer51** [comment]
Hi @tomaklutfu, could you describe to me what you are doing to trigger the error?

Also, from what I could read in the thread you linked and android-ndk/ndk#160, this seems to be a NDK issue, which is going to be fixed in NDK r13. I doubt we can do anything about it in the mean time.

**Comment by tomaklutfu** [comment]
It would be useful to instruct users to use atmost `platform 19` if packages uses `bsd_function`. I invoke below command with a standalone  toolchain including `platform 24` sysroot

```
make libs netlib TARGET=ARMV7 HOSTCC=gcc CC=arm-linux-androideabi-gcc FC=arm-linux-androideabi-gfortran USE_THREAD=0
```

I get this [error](https://gist.github.com/tomaklutfu/f69289d8bd91352159894b4eca7f7a93). `lapack-netlib` fails building some code.`platform 19` sysroot builds the library.

**Comment by buffer51** [comment]
That's probably a good idea, I'll add a section about choosing the right API level.

However I'm curious: I don't see any use of bsd_signal in the lapack-netlib files.
Is it hidden under one of the fortran calls like WRITE or FORMAT?

Edit: my mistake for closing/reopening the issue.

**Comment by tomaklutfu** [comment]
I think it is not directly related to library because it tries to link something to test existence of a function(in /lapack-netlib/INSTALL) but actual static library would not have that issue until it is linked against to produce an executable.
